# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.7
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_snowboy', [dirname(__file__)])
        except ImportError:
            import _snowboy
            return _snowboy
        if fp is not None:
            try:
                _mod = imp.load_module('_snowboy', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _snowboy = swig_import_helper()
    del swig_import_helper
else:
    import _snowboy
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0


class SnowboyDetect(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SnowboyDetect, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SnowboyDetect, name)
    __repr__ = _swig_repr

    def __init__(self, resource_filename, model_str):
        this = _snowboy.new_SnowboyDetect(resource_filename, model_str)
        try:
            self.this.append(this)
        except:
            self.this = this

    def Reset(self):
        return _snowboy.SnowboyDetect_Reset(self)

    def RunDetection(self, data):
        return _snowboy.SnowboyDetect_RunDetection(self, data)

    def SetSensitivity(self, sensitivity_str):
        return _snowboy.SnowboyDetect_SetSensitivity(self, sensitivity_str)

    def GetSensitivity(self):
        return _snowboy.SnowboyDetect_GetSensitivity(self)

    def SetAudioGain(self, audio_gain):
        return _snowboy.SnowboyDetect_SetAudioGain(self, audio_gain)

    def UpdateModel(self):
        return _snowboy.SnowboyDetect_UpdateModel(self)

    def NumHotwords(self):
        return _snowboy.SnowboyDetect_NumHotwords(self)

    def SampleRate(self):
        return _snowboy.SnowboyDetect_SampleRate(self)

    def NumChannels(self):
        return _snowboy.SnowboyDetect_NumChannels(self)

    def BitsPerSample(self):
        return _snowboy.SnowboyDetect_BitsPerSample(self)
    __swig_destroy__ = _snowboy.delete_SnowboyDetect
    __del__ = lambda self: None
SnowboyDetect_swigregister = _snowboy.SnowboyDetect_swigregister
SnowboyDetect_swigregister(SnowboyDetect)

class SnowboyPersonalDetect(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SnowboyPersonalDetect, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SnowboyPersonalDetect, name)
    __repr__ = _swig_repr

    def __init__(self, resource_filename, model_str):
        this = _snowboy.new_SnowboyPersonalDetect(resource_filename, model_str)
        try:
            self.this.append(this)
        except:
            self.this = this

    def Reset(self):
        return _snowboy.SnowboyPersonalDetect_Reset(self)

    def RunDetection(self, data):
        return _snowboy.SnowboyPersonalDetect_RunDetection(self, data)

    def SetSensitivity(self, sensitivity_str):
        return _snowboy.SnowboyPersonalDetect_SetSensitivity(self, sensitivity_str)

    def GetSensitivity(self):
        return _snowboy.SnowboyPersonalDetect_GetSensitivity(self)

    def SetAudioGain(self, audio_gain):
        return _snowboy.SnowboyPersonalDetect_SetAudioGain(self, audio_gain)

    def UpdateModel(self):
        return _snowboy.SnowboyPersonalDetect_UpdateModel(self)

    def NumHotwords(self):
        return _snowboy.SnowboyPersonalDetect_NumHotwords(self)

    def SampleRate(self):
        return _snowboy.SnowboyPersonalDetect_SampleRate(self)

    def NumChannels(self):
        return _snowboy.SnowboyPersonalDetect_NumChannels(self)

    def BitsPerSample(self):
        return _snowboy.SnowboyPersonalDetect_BitsPerSample(self)
    __swig_destroy__ = _snowboy.delete_SnowboyPersonalDetect
    __del__ = lambda self: None
SnowboyPersonalDetect_swigregister = _snowboy.SnowboyPersonalDetect_swigregister
SnowboyPersonalDetect_swigregister(SnowboyPersonalDetect)

class SnowboyUniversalDetect(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SnowboyUniversalDetect, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SnowboyUniversalDetect, name)
    __repr__ = _swig_repr

    def __init__(self, resource_filename, model_str):
        this = _snowboy.new_SnowboyUniversalDetect(resource_filename, model_str)
        try:
            self.this.append(this)
        except:
            self.this = this

    def Reset(self):
        return _snowboy.SnowboyUniversalDetect_Reset(self)

    def RunDetection(self, data):
        return _snowboy.SnowboyUniversalDetect_RunDetection(self, data)

    def SetSensitivity(self, sensitivity_str):
        return _snowboy.SnowboyUniversalDetect_SetSensitivity(self, sensitivity_str)

    def GetSensitivity(self):
        return _snowboy.SnowboyUniversalDetect_GetSensitivity(self)

    def SetAudioGain(self, audio_gain):
        return _snowboy.SnowboyUniversalDetect_SetAudioGain(self, audio_gain)

    def UpdateModel(self):
        return _snowboy.SnowboyUniversalDetect_UpdateModel(self)

    def NumHotwords(self):
        return _snowboy.SnowboyUniversalDetect_NumHotwords(self)

    def SampleRate(self):
        return _snowboy.SnowboyUniversalDetect_SampleRate(self)

    def NumChannels(self):
        return _snowboy.SnowboyUniversalDetect_NumChannels(self)

    def BitsPerSample(self):
        return _snowboy.SnowboyUniversalDetect_BitsPerSample(self)
    __swig_destroy__ = _snowboy.delete_SnowboyUniversalDetect
    __del__ = lambda self: None
SnowboyUniversalDetect_swigregister = _snowboy.SnowboyUniversalDetect_swigregister
SnowboyUniversalDetect_swigregister(SnowboyUniversalDetect)

class SnowboyTemplateCut(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SnowboyTemplateCut, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SnowboyTemplateCut, name)
    __repr__ = _swig_repr

    def __init__(self, resource_filename):
        this = _snowboy.new_SnowboyTemplateCut(resource_filename)
        try:
            self.this.append(this)
        except:
            self.this = this

    def Reset(self):
        return _snowboy.SnowboyTemplateCut_Reset(self)

    def CutTemplate(self, data):
        return _snowboy.SnowboyTemplateCut_CutTemplate(self, data)

    def SampleRate(self):
        return _snowboy.SnowboyTemplateCut_SampleRate(self)

    def NumChannels(self):
        return _snowboy.SnowboyTemplateCut_NumChannels(self)

    def BitsPerSample(self):
        return _snowboy.SnowboyTemplateCut_BitsPerSample(self)
    __swig_destroy__ = _snowboy.delete_SnowboyTemplateCut
    __del__ = lambda self: None
SnowboyTemplateCut_swigregister = _snowboy.SnowboyTemplateCut_swigregister
SnowboyTemplateCut_swigregister(SnowboyTemplateCut)

class SnowboyPersonalEnroll(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SnowboyPersonalEnroll, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SnowboyPersonalEnroll, name)
    __repr__ = _swig_repr

    def __init__(self, resource_filename, model_filename):
        this = _snowboy.new_SnowboyPersonalEnroll(resource_filename, model_filename)
        try:
            self.this.append(this)
        except:
            self.this = this

    def Reset(self):
        return _snowboy.SnowboyPersonalEnroll_Reset(self)

    def RunEnrollment(self, data):
        return _snowboy.SnowboyPersonalEnroll_RunEnrollment(self, data)

    def GetNumTemplates(self):
        return _snowboy.SnowboyPersonalEnroll_GetNumTemplates(self)

    def SampleRate(self):
        return _snowboy.SnowboyPersonalEnroll_SampleRate(self)

    def NumChannels(self):
        return _snowboy.SnowboyPersonalEnroll_NumChannels(self)

    def BitsPerSample(self):
        return _snowboy.SnowboyPersonalEnroll_BitsPerSample(self)
    __swig_destroy__ = _snowboy.delete_SnowboyPersonalEnroll
    __del__ = lambda self: None
SnowboyPersonalEnroll_swigregister = _snowboy.SnowboyPersonalEnroll_swigregister
SnowboyPersonalEnroll_swigregister(SnowboyPersonalEnroll)

class SnowboyVadBuffer(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SnowboyVadBuffer, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SnowboyVadBuffer, name)
    __repr__ = _swig_repr

    def __init__(self, resource_filename):
        this = _snowboy.new_SnowboyVadBuffer(resource_filename)
        try:
            self.this.append(this)
        except:
            self.this = this

    def RunVad(self, data):
        return _snowboy.SnowboyVadBuffer_RunVad(self, data)

    def Reset(self):
        return _snowboy.SnowboyVadBuffer_Reset(self)

    def ReadBuffer(self):
        return _snowboy.SnowboyVadBuffer_ReadBuffer(self)

    def SampleRate(self):
        return _snowboy.SnowboyVadBuffer_SampleRate(self)

    def NumChannels(self):
        return _snowboy.SnowboyVadBuffer_NumChannels(self)

    def BitsPerSample(self):
        return _snowboy.SnowboyVadBuffer_BitsPerSample(self)

    def SetAudioGain(self, audio_gain):
        return _snowboy.SnowboyVadBuffer_SetAudioGain(self, audio_gain)
    __swig_destroy__ = _snowboy.delete_SnowboyVadBuffer
    __del__ = lambda self: None
SnowboyVadBuffer_swigregister = _snowboy.SnowboyVadBuffer_swigregister
SnowboyVadBuffer_swigregister(SnowboyVadBuffer)

# This file is compatible with both classic and new-style classes.


